# Site settings
title: Professional Portfolio
email: marolahyrabe@gmail.com
description: >- 
  A professional portfolio showcasing projects, skills, and expertise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Custom variables
author: Andriamarolahy R.