domain: marolAI.github.io      
url: https://marolAI.github.io 
baseurl: /     
github: [metadata]

collections:
  authors:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag