domain: marolAI.github.io      
url: https://marolAI.github.io 
baseurl: /     
github: [metadata]

email: marolahyrabe@gmail.com
twitter_username: Massa_Be
github_username: marolAI

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

paginate: 3
paginate_path: "/page:num/"

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate